# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b749ef1ee7d20fb1f768bf664f7b26f49a084add431cf2d0677a22c7ea7d0e2a3f03b02c431877b23c7b2314b586796ba7ac1fc772a4504b600601166a35eb2e

test:
  secret_key_base: 2f95ac9f28da932edff0035daf279f50280560f58bebb49198a7b89f9243bbc66128f3e99c4f1e3676e9c5e575ad1ea5bd35fe257d2d89c48199bd19dc0d584c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
